version: '3.8'

networks:
  dropclick:
    name: dropclick

services:
  dropclick_db:
    image: mysql
    container_name: dropclick_db
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    # env_file:
    #   - .env
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE:'${MYSQL_DB_NAME}'
      - MYSQL_PASSWORD:'${MYSQL_PASSWORD}'
      - MYSQL_ROOT_PASSWORD:'${MYSQL_ROOT_PASSWORD}'
    ports:
      - 3306:3306
    networks:
      - dropclick

  dropclick_node:
    container_name: dropclick_node
    restart: always
    build:
      context: .
      dockerfile: DockerFile
    env_file:
      - .env
    ports:
      - 4555:4555
    volumes:
      - .:/home/node/app
    depends_on:
      - dropclick_db 
    networks:
      - dropclick

volumes:
  data: